# What is numpy

Numpy is python library

it used for working with arrays

numpy short for Numerical Python

It's python's library used for working with arrays
    
also has fun to work in domain like linear algebra, fourier transforn, and matrices

# why to use numpy


- we have list already to serve the purpose of array, nut they are quite slow to process
- but numpy provide an array object that is 50x times faster than traditional python list
- the array obj in python is called ndarray,it provides a lot of supporting func that make ndarray very easy
- arrays are frequently used in Data Sci where speed and resources are very imp

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

# Why is NumPy Faster Than Lists?


- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This locality is called locality of reference in computer science
- This is the main reason why NumPy is faster than lists

# Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are 
written in C or C++.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# checking numpy version

In [3]:
print(np.__version__)

1.21.5


# Create a NumPy ndarray Object

 NumPy is used to work with arrays. The array object in NumPy is called ndarray.

 We can create a NumPy ndarray object by using the array() function.

In [8]:
arr = np.array([3,5,6,71,5,6]) #to create array we can pass a list, tuple or any array-like object into array method
# arr
type(arr)

numpy.ndarray

# Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays

 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
import numpy as np
arr = np.array(42) # 0-D 
print(arr)

42


# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# 2-D Array

An array that has 1-D arrays as its elements is called a 2-D array

These are often used to represent matrix or 2nd order tensors.

In [12]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check number of Dimensions

ndim attribute that returns no. of dimensions thay array have.

In [14]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions
when the array is created, you can define the number of dimentiosn by using the ndmin arg.

In [16]:
import numpy as np
arr = np.array([1,3,3],ndmin=5) #hint: number of brackets = dim of arr
print(arr)
print('number of dimension : ',arr.ndim)

[[[[[1 3 3]]]]]
number of dimension :  5


# NumPy Array Indexing

Access Array Elements:
    
Array indexing is the same as accessing an array element.
u can access an array ele by referring to its index number.
same like list, it's starts with 0th index

In [18]:
import numpy as np
arr = np.array([2,3,4,5])
print(arr[0])
print(arr[2] + arr[3])

2
9


# Access 2D Array

To access elements from 2D arrays we can use comma seprated int respresting the dimesnion and the index of the element.


In [19]:
import numpy as np
arr = np.array([[3,4,5] ,[5,6,7]])
print('2nd ele of 1st row : ',arr[0,1])

2nd ele of 1st row :  4


# Access 3D Arrays

In [22]:
import numpy as np
arr = np.array([[[5,24,4],[7,5,7]],[[2,3,4],[7,6,5]]])
print(arr[0,1,2])

7


Negative indexing is just like list

# NumPy Array slicing

slicing arrays:

slicing in python means taking ele from one given index to another given index

slicing - [start,end,step]

In [24]:
import numpy as np
arr = np.array([1,2,4,5,7,5])
print(arr[1:5]) #it includes the start index, but excludes the end index
print(arr[4:])
print(arr[:4])

[2 4 5 7]
[7 5]


Negative slicing is same as list

# Step

it uses to determine the step of slicing

In [29]:
import numpy as np
arr = np.array([5,2,7,5,3])
print(arr[1:5:1])# steping 1 mns No change,steping 2 mns at alternative
print(arr[::2])

[2 7 5 3]
[5 7 3]


In [33]:
# slicing 2D array
import numpy as np
arr = np.array([[3,4,5,3,4],[7,5,4,3,8]])
print(arr[1,1:3])
print(arr[0:2,2])#0:2 mns both array and in that 2 mns of each array

[5 4]


In [35]:
import numpy as np
arr = np.array([[3,6,4,6,4,3],[2,4,5,9,8,6]])
print(arr[0:2,1:4])

[[6 4 6]
 [4 5 9]]


# NumPy Data Types

by default python have following datatypes:

1) strings - 'abcd'
2) integer - '-1,-4,3,4'
3) float - 2.4,3.5
4) boolean - True or False
5) complex - 1.0+3.5j,4.3+2.5j

NumPy has some extra data types, can refer to data type with one char like i for int

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- o - object
- s - string
- u - unicode sting
- v - fixed chunk of memory for other type(void)

# Checking the Data Type of an Array

In [37]:
import numpy as np
arr = np.array([3,4,5,7])
arr1 = np.array(['apple','banana','cherry'])
print(arr1.dtype)
print(arr.dtype)

<U6
int32


Creating Arrays with a Custom Data Type

In [40]:
arr3 = np.array([5,3,7,9,2],dtype='S')
print(arr3)
print(arr3.dtype)

[b'5' b'3' b'7' b'9' b'2']
|S1


In [41]:
# For i, u, f, S and U we can define size as well.
arr4 = np.array([1, 2, 3, 4], dtype='i4')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays

astype() : astype() fun creates a copy of the array, and the allow u to specify the data type as a para.

In [45]:
arr5 = np.array([1.2,4.5,6.4])
newarr = arr5.astype('i')
newarr1 = arr5.astype(bool)
newarr2 = arr5.astype(int)
print(newarr)
print(newarr.dtype)


[1 4 6]
int32
